apiVersion: dragonfly.computer/v1
kind: Template
metadata:
  name: debian-13
spec:
  timeout: 9800
  actions:
    - action: image2disk
      url: "https://cloud.debian.org/images/cloud/trixie/daily/latest/debian-13-genericcloud-amd64-daily.tar.xz"
      disk: auto
      timeout: 9600

    - action: writefile
      path: /etc/cloud/cloud.cfg.d/10_dragonfly.cfg
      partition: 2
      content: |
        datasource:
          Ec2:
            metadata_urls: ["http://{{ server }}:50061"]
            strict_id: false
        manage_etc_hosts: localhost
        warnings:
          dsid_missing_source: off
        users:
          - default
        disable_root: true
        ssh_import_id:
          - gh:zorlin
          - gh:michatinkers
        packages:
          - qemu-guest-agent
        runcmd:
          - systemctl enable qemu-guest-agent
          - systemctl start qemu-guest-agent
      mode: "0600"
      timeout: 90

    - action: writefile
      path: /etc/cloud/ds-identify.cfg
      partition: 2
      content: |
        datasource: Ec2
      mode: "0600"
      timeout: 90

    - action: writefile
      path: /etc/network/interfaces.d/eth0
      partition: 2
      content: |
        auto eth0
        iface eth0 inet dhcp
      mode: "0644"
      timeout: 90

    - action: kexec
      partition: 2
      cmdline: "ro quiet"
      timeout: 90
