apiVersion: dragonfly.computer/v1
kind: Template
metadata:
  name: proxmox
spec:
  timeout: 14400
  actions:
    # Proxmox VE 9 on Debian 13 Trixie — one-boot provisioning
    #
    # 1. Image disk with Debian 13 cloud image
    # 2. Write cloud-init seed data (user, SSH keys, network)
    # 3. Activate chroot on the imaged disk
    # 4. Run Jetpack playbook inside chroot to install Proxmox VE 9
    # 5. Tear down chroot
    # 6. Boot into finished Proxmox system

    - action: image2disk
      url: "https://cloud.debian.org/images/cloud/trixie/daily/latest/debian-13-generic-amd64-daily.tar.xz"
      disk: auto
      timeout: 9600

    - action: writefile
      path: /etc/cloud/ds-identify.cfg
      partition: 1
      content: |
        datasource: NoCloud
      mode: "0644"
      timeout: 90

    - action: writefile
      path: /var/lib/cloud/seed/nocloud/meta-data
      partition: 1
      content: |
        instance-id: {{ instance_id }}
        local-hostname: {{ friendly_name }}
      mode: "0644"
      timeout: 90

    - action: writefile
      path: /var/lib/cloud/seed/nocloud/network-config
      partition: 1
      content: |
        {{ network_config_cloudinit }}
      mode: "0644"
      timeout: 90

    - action: writefile
      path: /var/lib/cloud/seed/nocloud/user-data
      partition: 1
      content: |
        #cloud-config
        manage_etc_hosts: false
        users:
          - name: "{{ default_user }}"
            sudo: ALL=(ALL) NOPASSWD:ALL
            shell: /bin/bash
            lock_passwd: false
            ssh_authorized_keys: {{ ssh_authorized_keys }}
            ssh_import_id: {{ ssh_import_id }}
        disable_root: false
        chpasswd:
          expire: false
          users:
            - name: "{{ default_user }}"
              password: "{{ default_password }}"
              type: text
            - name: root
              password: "{{ default_password }}"
              type: text
        ssh_pwauth: {{ ssh_pwauth }}
      mode: "0644"
      timeout: 90

    # Mount the imaged disk and activate chroot environment
    - action: chroot
      disk: "{{ destination_disk }}"
      partition: 1
      timeout: 120

    # Run Jetpack inside the chroot to install Proxmox VE 9
    - action: jetpack
      url: "http://{{ server }}/playbooks/debian-to-proxmox.tar.gz"
      timeout: 7200

    # Tear down the chroot
    - action: chroot
      teardown: true
      timeout: 120

    # Boot into the finished Proxmox VE system
    - action: kexec
      timeout: 120
