apiVersion: dragonfly.computer/v1
kind: Template
metadata:
  name: ubuntu-2204
spec:
  timeout: 9800
  actions:
    - action: image2disk
      url: "https://cloud-images.ubuntu.com/jammy/current/jammy-server-cloudimg-amd64.img"
      disk: auto
      timeout: 9600

    - action: writefile
      path: /etc/cloud/cloud.cfg.d/10_dragonfly.cfg
      partition: 1
      content: |
        datasource:
          Ec2:
            metadata_urls: ["http://{{ server }}:50061"]
            strict_id: false
        manage_etc_hosts: localhost
        warnings:
          dsid_missing_source: off
        users:
          - default
        disable_root: true
        ssh_import_id:
          - gh:zorlin
          - gh:michatinkers
        packages:
          - qemu-guest-agent
        runcmd:
          - systemctl enable qemu-guest-agent
          - systemctl start qemu-guest-agent
      mode: "0600"
      timeout: 90

    - action: writefile
      path: /etc/cloud/ds-identify.cfg
      partition: 1
      content: |
        datasource: Ec2
      mode: "0600"
      timeout: 90

    - action: writefile
      path: /etc/netplan/config.yaml
      partition: 1
      content: |
        network:
          version: 2
          renderer: networkd
          ethernets:
            id0:
              match:
                name: en*
              dhcp4: true
      mode: "0644"
      timeout: 90

    - action: kexec
      partition: 1
      cmdline: "ro quiet"
      timeout: 90
