apiVersion: dragonfly.computer/v1
kind: Template
metadata:
  name: ubuntu-2204
spec:
  timeout: 9800
  actions:
    - action: image2disk
      url: "https://cloud-images.ubuntu.com/jammy/current/jammy-server-cloudimg-amd64.img"
      disk: auto
      timeout: 9600

    - action: writefile
      path: /etc/cloud/ds-identify.cfg
      partition: 1
      content: |
        datasource: NoCloud
      mode: "0644"
      timeout: 90

    - action: writefile
      path: /var/lib/cloud/seed/nocloud/meta-data
      partition: 1
      content: |
        instance-id: {{ instance_id }}
        local-hostname: {{ friendly_name }}
      mode: "0644"
      timeout: 90

    - action: writefile
      path: /var/lib/cloud/seed/nocloud/user-data
      partition: 1
      content: |
        #cloud-config
        manage_etc_hosts: localhost
        users:
          - name: "{{ default_user }}"
            sudo: ALL=(ALL) NOPASSWD:ALL
            shell: /bin/bash
            lock_passwd: false
            ssh_authorized_keys: {{ ssh_authorized_keys }}
        disable_root: false
        ssh_import_id: {{ ssh_import_id }}
        chpasswd:
          expire: false
          users:
            - name: "{{ default_user }}"
              password: "{{ default_password }}"
              type: text
        ssh_pwauth: {{ ssh_pwauth }}
        packages:
          - qemu-guest-agent
        runcmd:
          - systemctl enable qemu-guest-agent
          - systemctl start qemu-guest-agent
      mode: "0644"
      timeout: 90

    - action: writefile
      path: /etc/netplan/config.yaml
      partition: 1
      content: |
        network:
          version: 2
          renderer: networkd
          ethernets:
            id0:
              match:
                name: en*
              dhcp4: true
      mode: "0644"
      timeout: 90

    - action: kexec
      partition: 1
      cmdline: "ro quiet"
      timeout: 90
